### ISSUE TITLE
Skip inheritances is not set. This may throw an error, if basedir is set to "." and pug-inheritance is resolving files also in package folders.

### ISSUE THREAD

**Issue by ruslanxdev** [adammockor/pug-inheritance#12]
Message:
> Skip inheritances is not set. This may throw an error, if basedir is set to "." and pug-inheritance is resolving files also in package folders.

Gulpfile.js:
``` js
gulp.task('pug', function(){
	return gulp.src('src/pug/**/*.pug')
		.pipe(plumber())
		.pipe(changed(path.main, {extension: '.html'}))
        .pipe(cached('pug'))
        .pipe(pugInheritance({basedir: 'src/pug'}))
		.pipe(data(function(file) {
			return JSON.parse(fs.readFileSync('src/json/data.json'));
		}))
		.pipe(filter(function (file) {
            return !/\/_/.test(file.path) && !/^_/.test(file.relative);
        }))
		.pipe(pug({
			basedir: 'src/pug',
			pretty: '\t'
		}))
		.pipe(gulp.dest(path.main))
		.pipe(livereload());
});
```
What am I doing wrong?

**Comment by adammockor** [comment]
Pass there skip property for example like this: 

```
.pipe(pugInheritance({basedir: 'src/pug', skip: 'node_modules'}}))
```

But we should do this differently to avoid this false positive message.

**Comment by ruslanxdev** [comment]
With gulp-debug:

``` js
gulp.task('pug', function(){
    return gulp.src('src/pug/**/*.pug')
        .pipe(plumber())
        .pipe(changed(path.main, {extension: '.html'}))
        .pipe(cached('pug'))
        .pipe(debug({title: 'debug-before'}))
        .pipe(pugInheritance({basedir: 'src/pug', skip: 'node_modules'}))
        .pipe(debug({title: 'debug-after'}))
        .pipe(data(function(file) {
            return JSON.parse(fs.readFileSync('src/json/data.json'));
        }))
        .pipe(filter(function (file) {
            return !/\/_/.test(file.path) && !/^_/.test(file.relative);
        }))
        .pipe(pug({
            basedir: 'src/pug',
            pretty: '\t'
        }))
        .pipe(gulp.dest(path.main))
        .pipe(livereload());
});
```

Result:

``` bash
[21:52:34] Starting 'pug'...
[21:52:34] Finished 'watch-pug' after 27 ms
[21:52:34] debug-before src/pug/_includes/footer.pug
[21:52:34] debug-before src/pug/_includes/head-public.pug
[21:52:34] debug-before src/pug/_includes/head-watch.pug
[21:52:34] debug-before src/pug/_includes/head.pug
[21:52:34] debug-before src/pug/_includes/header.pug
[21:52:34] debug-before src/pug/_includes/scripts-public.pug
[21:52:34] debug-before src/pug/_includes/scripts-watch.pug
[21:52:34] debug-before src/pug/_includes/scripts.pug
[21:52:34] Finished 'bootstrap-js' after 339 ms
[21:52:34] debug-before src/pug/_layouts/default.pug
[21:52:34] debug-before src/pug/_layouts/page.pug
[21:52:34] debug-before src/pug/_layouts/section.pug
[21:52:34] debug-before 11 items
[21:54:22] debug-after src/pug/_includes/footer.pug
[21:54:22] bootstrap.css was reloaded.
[21:54:22] Finished 'bootstrap-scss' after 1.8 min
[21:54:22] Starting 'bootstrap'...
[21:54:22] Finished 'bootstrap' after 20 μs
[21:54:22] debug-after src/pug/_layouts/default.pug
[21:54:22] debug-after src/pug/_layouts/page.pug
[21:54:22] debug-after src/pug/duolingo/1/index.pug
[21:54:23] debug-after src/pug/duolingo/2/index.pug
[21:54:23] debug-after src/pug/duolingo/3/index.pug
[21:54:24] index.html was reloaded.
[21:54:24] debug-after src/pug/duolingo/4/index.pug
[21:54:24] index.html was reloaded.
[21:54:24] debug-after src/pug/duolingo/5/index.pug
[21:54:24] debug-after src/pug/duolingo/6/index.pug
[21:54:24] index.html was reloaded.
[21:54:24] debug-after src/pug/duolingo/7/index.pug
[21:54:25] debug-after src/pug/duolingo/8/index.pug
[21:54:25] index.html was reloaded.
[21:54:25] debug-after src/pug/duolingo/9/index.pug
[21:54:25] debug-after src/pug/sabirov-sam/0/index.pug
[21:54:26] index.html was reloaded.
[21:54:26] debug-after src/pug/sabirov-sam/1/1/index.pug
[21:54:26] debug-after src/pug/sabirov-sam/1/2/index.pug
[21:54:26] index.html was reloaded.
[21:54:26] debug-after src/pug/sabirov-sam/1/3/index.pug
[21:54:26] debug-after src/pug/sabirov-sam/1/4/index.pug
[21:54:26] index.html was reloaded.
[21:54:26] debug-after src/pug/sabirov-sam/1/index.pug
[21:54:27] debug-after src/pug/_layouts/section.pug
[21:54:27] debug-after src/pug/duolingo/index.pug
[21:54:27] index.html was reloaded.
[21:54:27] debug-after src/pug/index.pug
[21:54:27] debug-after src/pug/sabirov-sam/index.pug
[21:54:27] index.html was reloaded.
[21:54:27] debug-after src/pug/tatarchannel/index.pug
[21:54:27] debug-after src/pug/_includes/head-public.pug
[21:54:27] index.html was reloaded.
[21:54:27] debug-after src/pug/_includes/head-watch.pug
[21:54:27] debug-after src/pug/_includes/head.pug
[21:54:27] debug-after src/pug/_includes/header.pug
[21:54:27] index.html was reloaded.
[21:54:27] debug-after src/pug/_includes/scripts-public.pug
[21:54:27] debug-after src/pug/_includes/scripts-watch.pug
[21:54:27] index.html was reloaded.
[21:54:27] debug-after src/pug/_includes/scripts.pug
[21:54:27] debug-after 30 items
[21:54:27] index.html was reloaded.
[21:54:27] index.html was reloaded.
[21:54:27] index.html was reloaded.
[21:54:27] index.html was reloaded.
[21:54:27] index.html was reloaded.
[21:54:27] index.html was reloaded.
[21:54:27] index.html was reloaded.
[21:54:27] Finished 'pug' after 1.88 min
```

**Comment by adammockor** [comment]
1. Please run `gulp-debug` after filter function, that's most important, what files are left there.
2. Is this taking that long after multiple runs in watching mode?

I am successfull with workflow like this, but I am filtering files by different conditions:

```
var dataFileHashCache = null;

// Compile pug to html

gulp.task('templates', function() {
  // compare data file hash with cached data file to determine if file changes
  var dataFileHash = md5File.sync(config.templatesData.dataPath);
  var isDataFileChanged = (dataFileHashCache === null) || (dataFileHashCache !== dataFileHash);
  dataFileHashCache = dataFileHash;

  return gulp.src(config.templates.src, { base: config.templates.base })
    .pipe(plumber(handleError))
    .pipe(gulpif(watch.isWatching && !isDataFileChanged, changed('.tmp', {extension: '.html'})))
    .pipe(gulpif(watch.isWatching && !isDataFileChanged, cached('pug')))
    .pipe(gulpif(watch.isWatching && !isDataFileChanged, pugInheritance({basedir: config.templates.base, skip: 'node_modules'})))
    .pipe(filter(function (file) {
      return /^[^\\\/]+\.pug$/.test(file.relative) || /^styleguide[\\\/][^\\\/]+\.pug$/.test(file.relative)
    }))
    .pipe(data(function() {
      var data = yaml.safeLoad(fs.readFileSync(config.templatesData.dataPath, 'utf8'));
      var helpers = require(config.templatesData.helpersPath);
      return _.assign({}, data, helpers);
    }))
    .pipe(pug(config.templates.cfg))
    .pipe(gulp.dest(config.templates.dest));
});
```

**Comment by pure180** [comment]
First of all, which plugin are you using, [gulp-pug-inheritance](https://www.npmjs.com/package/gulp-pug-inheritance) or [gulp-jade-inheritance](https://www.npmjs.com/package/gulp-jade-inheritance)?

I'm using [gulp-pug-inheritance](https://www.npmjs.com/package/gulp-pug-inheritance) a lot in production and iam not facing any issues. Guess there is something wrong in your gulpfile, please check it.

[Here](https://github.com/pure180/gulp-pug-inheritance-test) you can find a working example, for now it is all fine with it. I added gulp-debug, gulp-notify and gulp-plumber right in the moment, to get behind your problem. This is my result.

```
[20:23:56] Using gulpfile H:\GitHub\gulp-pug-inheritance-test\gulpfile.js
[20:23:56] Starting 'setWatch'...
[20:23:56] Finished 'setWatch' after 76 μs
[20:23:56] Starting 'jade'...
[20:23:56] debug-before app\_extends\layout.pug
[20:23:56] debug-before app\_includes\section1.pug
[20:23:56] debug-before 2 items
[20:23:56] debug-after app\_extends\layout.pug
[20:23:56] debug-after app\index.pug
[20:23:56] debug-after-filter app\index.pug
[20:23:56] debug-after app\_includes\section1.pug
[20:23:56] debug-after 3 items
[20:23:56] debug-after-filter 1 item
[20:23:56] gulp-notify: [Gulp notification] Served "H:\GitHub\gulp-pug-inheritance-test\dist\index.html"
[20:23:56] Finished 'jade' after 152 ms
[20:23:56] Starting 'watch'...
[20:23:56] Finished 'watch' after 14 ms
```

> But we should do this differently to avoid this false positive message.

@adammockor, i dont thing that this is needed and / or necessary. I often use different custom folders to install my node modules. Sometimes i split them i many different folders, depending on my bundle. People should read the documentation... ;-)

**Comment by ruslanxdev** [comment]
@pure180 Test 1 is good.

```
[22:49:29] Using gulpfile ~/Home/gulp-pug-inheritance-test/gulpfile.js
[22:49:29] Starting 'setWatch'...
[22:49:29] Finished 'setWatch' after 231 μs
[22:49:29] Starting 'jade'...
[22:49:29] debug-before app/_extends/layout.pug
[22:49:29] debug-before app/_includes/section1.pug
[22:49:29] debug-before 2 items
[22:49:29] debug-after app/_extends/layout.pug
[22:49:29] debug-after app/index.pug
[22:49:29] debug-after-filter app/index.pug
[22:49:29] debug-after app/_includes/section1.pug
[22:49:29] debug-after 3 items
[22:49:29] debug-after-filter 1 item
[22:49:29] gulp-notify: [Gulp notification] Served "/Users/gallo/Home/gulp-pug-inheritance-test/dist/index.html"
[22:49:29] Finished 'jade' after 639 ms
[22:49:29] Starting 'watch'...
[22:49:29] Finished 'watch' after 70 ms
```

**Comment by ruslanxdev** [comment]
@pure180 Test 2 (with my 30 files) is no good.

```
[22:52:18] Using gulpfile ~/Home/gulp-pug-inheritance-test/gulpfile.js
[22:52:18] Starting 'setWatch'...
[22:52:18] Finished 'setWatch' after 90 μs
[22:52:18] Starting 'jade'...
[22:52:18] debug-before app/_includes/footer.pug
[22:52:18] debug-before app/_includes/head-public.pug
[22:52:18] debug-before app/_includes/head-watch.pug
[22:52:18] debug-before app/_includes/head.pug
[22:52:18] debug-before app/_includes/header.pug
[22:52:18] debug-before app/_includes/scripts-public.pug
[22:52:18] debug-before app/_includes/scripts-watch.pug
[22:52:18] debug-before app/_includes/scripts.pug
[22:52:18] debug-before app/_layouts/default.pug
[22:52:18] debug-before app/_layouts/page.pug
[22:52:18] debug-before app/_layouts/section.pug
[22:52:18] debug-before app/duolingo/index.pug
[22:52:18] debug-before app/sabirov-sam/index.pug
[22:52:18] debug-before app/tatarchannel/index.pug
[22:52:18] debug-before app/duolingo/1/index.pug
[22:52:18] debug-before app/duolingo/2/index.pug
[22:52:18] debug-before app/duolingo/3/index.pug
[22:52:18] debug-before app/duolingo/4/index.pug
[22:52:18] debug-before app/duolingo/5/index.pug
[22:52:18] debug-before app/duolingo/6/index.pug
[22:52:18] debug-before app/duolingo/7/index.pug
[22:52:18] debug-before app/duolingo/8/index.pug
[22:52:18] debug-before app/duolingo/9/index.pug
[22:52:18] debug-before app/sabirov-sam/0/index.pug
[22:52:18] debug-before app/sabirov-sam/1/index.pug
[22:52:18] debug-before app/sabirov-sam/1/1/index.pug
[22:52:18] debug-before app/sabirov-sam/1/2/index.pug
[22:52:18] debug-before app/sabirov-sam/1/3/index.pug
[22:52:18] debug-before app/sabirov-sam/1/4/index.pug
[22:52:18] debug-before 29 items
[22:54:04] debug-after app/_includes/footer.pug
[22:54:04] debug-after app/_layouts/default.pug
[22:54:04] debug-after app/_layouts/page.pug
[22:54:04] debug-after app/duolingo/1/index.pug
[22:54:04] debug-after-filter app/duolingo/1/index.pug
/Users/gallo/Home/gulp-pug-inheritance-test/gulpfile.js:18
            gutil.log(error.message);
            ^

ReferenceError: gutil is not defined
    at DestroyableTransform.errorHandler (/Users/gallo/Home/gulp-pug-inheritance-test/gulpfile.js:18:13)
    at emitOne (events.js:82:20)
    at DestroyableTransform.emit (events.js:169:7)
    at onwriteError (/Users/gallo/Home/gulp-pug-inheritance-test/node_modules/gulp-pug/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:322:10)
    at onwrite (/Users/gallo/Home/gulp-pug-inheritance-test/node_modules/gulp-pug/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:339:11)
    at WritableState.onwrite (/Users/gallo/Home/gulp-pug-inheritance-test/node_modules/gulp-pug/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:123:5)
    at afterTransform (/Users/gallo/Home/gulp-pug-inheritance-test/node_modules/gulp-pug/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:81:3)
    at TransformState.afterTransform (/Users/gallo/Home/gulp-pug-inheritance-test/node_modules/gulp-pug/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:58:12)
    at DestroyableTransform.compilePug (/Users/gallo/Home/gulp-pug-inheritance-test/node_modules/gulp-pug/index.js:38:16)
    at DestroyableTransform.Transform._read (/Users/gallo/Home/gulp-pug-inheritance-test/node_modules/gulp-pug/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:159:10)
```

**Comment by pure180** [comment]
It seems that there is some thing wrong with gulp-filter, because it breaks the build after initializing the first file.
I have a build on work with more then 250 pug files, it takes time to build them. But don't breaks the build. I can take a look at it on Monday.

**Comment by ruslanxdev** [comment]
@pure180 Test 3 (with my 30 files, gulp-util and `jade({basedir: 'app'})`) is the same:

```
[23:07:32] Using gulpfile ~/Home/gulp-pug-inheritance-test/gulpfile.js
[23:07:32] Starting 'setWatch'...
[23:07:32] Finished 'setWatch' after 81 μs
[23:07:32] Starting 'jade'...
[23:07:32] debug-before app/_includes/footer.pug
[23:07:32] debug-before app/_includes/head-public.pug
[23:07:32] debug-before app/_includes/head-watch.pug
[23:07:32] debug-before app/_includes/head.pug
[23:07:32] debug-before app/_includes/header.pug
[23:07:32] debug-before app/_includes/scripts-public.pug
[23:07:32] debug-before app/_includes/scripts-watch.pug
[23:07:32] debug-before app/_includes/scripts.pug
[23:07:32] debug-before app/_layouts/default.pug
[23:07:32] debug-before app/_layouts/page.pug
[23:07:32] debug-before app/_layouts/section.pug
[23:07:32] debug-before app/duolingo/index.pug
[23:07:32] debug-before app/tatarchannel/index.pug
[23:07:32] debug-before app/sabirov-sam/index.pug
[23:07:32] debug-before app/duolingo/1/index.pug
[23:07:32] debug-before app/duolingo/2/index.pug
[23:07:32] debug-before app/duolingo/3/index.pug
[23:07:32] debug-before app/duolingo/4/index.pug
[23:07:32] debug-before app/duolingo/5/index.pug
[23:07:32] debug-before app/duolingo/6/index.pug
[23:07:32] debug-before app/duolingo/7/index.pug
[23:07:32] debug-before app/duolingo/8/index.pug
[23:07:32] debug-before app/duolingo/9/index.pug
[23:07:32] debug-before app/sabirov-sam/0/index.pug
[23:07:32] debug-before app/sabirov-sam/1/index.pug
[23:07:32] debug-before app/sabirov-sam/1/1/index.pug
[23:07:32] debug-before app/sabirov-sam/1/2/index.pug
[23:07:32] debug-before app/sabirov-sam/1/3/index.pug
[23:07:32] debug-before app/sabirov-sam/1/4/index.pug
[23:07:32] debug-before 29 items
[23:09:02] debug-after app/_includes/footer.pug
[23:09:02] debug-after app/_layouts/default.pug
[23:09:02] debug-after app/_layouts/page.pug
[23:09:02] debug-after app/duolingo/1/index.pug
[23:09:02] debug-after-filter app/duolingo/1/index.pug
[23:09:03] debug-after app/duolingo/2/index.pug
[23:09:03] debug-after-filter app/duolingo/2/index.pug
[23:09:03] debug-after app/duolingo/3/index.pug
[23:09:03] debug-after-filter app/duolingo/3/index.pug
[23:09:04] debug-after app/duolingo/4/index.pug
[23:09:04] debug-after-filter app/duolingo/4/index.pug
[23:09:04] gulp-notify: [Gulp notification] Served "/Users/gallo/Home/gulp-pug-inheritance-test/dist/duolingo/1/index.html"
[23:09:04] debug-after app/duolingo/5/index.pug
[23:09:04] debug-after-filter app/duolingo/5/index.pug
[23:09:04] debug-after app/duolingo/6/index.pug
[23:09:04] debug-after-filter app/duolingo/6/index.pug
[23:09:05] debug-after app/duolingo/7/index.pug
[23:09:05] debug-after-filter app/duolingo/7/index.pug
[23:09:05] gulp-notify: [Gulp notification] Served "/Users/gallo/Home/gulp-pug-inheritance-test/dist/duolingo/2/index.html"
[23:09:05] debug-after app/duolingo/8/index.pug
[23:09:05] debug-after-filter app/duolingo/8/index.pug
[23:09:05] debug-after app/duolingo/9/index.pug
[23:09:05] debug-after-filter app/duolingo/9/index.pug
[23:09:06] gulp-notify: [Gulp notification] Served "/Users/gallo/Home/gulp-pug-inheritance-test/dist/duolingo/3/index.html"
[23:09:06] debug-after app/sabirov-sam/0/index.pug
[23:09:06] debug-after-filter app/sabirov-sam/0/index.pug
[23:09:06] debug-after app/sabirov-sam/1/1/index.pug
[23:09:06] debug-after-filter app/sabirov-sam/1/1/index.pug
[23:09:06] gulp-notify: [Gulp notification] Served "/Users/gallo/Home/gulp-pug-inheritance-test/dist/duolingo/4/index.html"
[23:09:06] debug-after app/sabirov-sam/1/2/index.pug
[23:09:06] debug-after-filter app/sabirov-sam/1/2/index.pug
[23:09:07] debug-after app/sabirov-sam/1/3/index.pug
[23:09:07] debug-after-filter app/sabirov-sam/1/3/index.pug
[23:09:07] gulp-notify: [Gulp notification] Served "/Users/gallo/Home/gulp-pug-inheritance-test/dist/duolingo/5/index.html"
[23:09:07] debug-after app/sabirov-sam/1/4/index.pug
[23:09:07] debug-after-filter app/sabirov-sam/1/4/index.pug
[23:09:07] debug-after app/sabirov-sam/1/index.pug
[23:09:07] debug-after-filter app/sabirov-sam/1/index.pug
[23:09:07] gulp-notify: [Gulp notification] Served "/Users/gallo/Home/gulp-pug-inheritance-test/dist/duolingo/6/index.html"
[23:09:07] debug-after app/_layouts/section.pug
[23:09:07] debug-after app/duolingo/index.pug
[23:09:07] debug-after-filter app/duolingo/index.pug
[23:09:07] gulp-notify: [Gulp notification] Served "/Users/gallo/Home/gulp-pug-inheritance-test/dist/duolingo/7/index.html"
[23:09:07] debug-after app/index.pug
[23:09:07] debug-after-filter app/index.pug
[23:09:07] debug-after app/sabirov-sam/index.pug
[23:09:07] debug-after-filter app/sabirov-sam/index.pug
[23:09:08] debug-after app/tatarchannel/index.pug
[23:09:08] debug-after-filter app/tatarchannel/index.pug
[23:09:08] gulp-notify: [Gulp notification] Served "/Users/gallo/Home/gulp-pug-inheritance-test/dist/duolingo/8/index.html"
[23:09:08] debug-after app/_includes/head-public.pug
[23:09:08] gulp-notify: [Gulp notification] Served "/Users/gallo/Home/gulp-pug-inheritance-test/dist/duolingo/9/index.html"
[23:09:08] debug-after app/_includes/head-watch.pug
[23:09:08] debug-after app/_includes/head.pug
[23:09:08] debug-after app/_includes/header.pug
[23:09:08] gulp-notify: [Gulp notification] Served "/Users/gallo/Home/gulp-pug-inheritance-test/dist/sabirov-sam/0/index.html"
[23:09:08] debug-after app/_includes/scripts-public.pug
[23:09:08] debug-after app/_includes/scripts-watch.pug
[23:09:08] gulp-notify: [Gulp notification] Served "/Users/gallo/Home/gulp-pug-inheritance-test/dist/sabirov-sam/1/1/index.html"
[23:09:08] debug-after app/_includes/scripts.pug
[23:09:08] debug-after 30 items
[23:09:08] debug-after-filter 19 items
[23:09:08] gulp-notify: [Gulp notification] Served "/Users/gallo/Home/gulp-pug-inheritance-test/dist/sabirov-sam/1/2/index.html"
[23:09:08] gulp-notify: [Gulp notification] Served "/Users/gallo/Home/gulp-pug-inheritance-test/dist/sabirov-sam/1/3/index.html"
[23:09:08] gulp-notify: [Gulp notification] Served "/Users/gallo/Home/gulp-pug-inheritance-test/dist/sabirov-sam/1/4/index.html"
[23:09:08] gulp-notify: [Gulp notification] Served "/Users/gallo/Home/gulp-pug-inheritance-test/dist/sabirov-sam/1/index.html"
[23:09:08] gulp-notify: [Gulp notification] Served "/Users/gallo/Home/gulp-pug-inheritance-test/dist/duolingo/index.html"
[23:09:09] gulp-notify: [Gulp notification] Served "/Users/gallo/Home/gulp-pug-inheritance-test/dist/index.html"
[23:09:09] gulp-notify: [Gulp notification] Served "/Users/gallo/Home/gulp-pug-inheritance-test/dist/sabirov-sam/index.html"
[23:09:09] gulp-notify: [Gulp notification] Served "/Users/gallo/Home/gulp-pug-inheritance-test/dist/tatarchannel/index.html"
[23:09:09] Finished 'jade' after 1.6 min
[23:09:09] Starting 'watch'...
[23:09:09] Finished 'watch' after 209 ms
```

**Comment by ruslanxdev** [comment]
@pure180 @adammockor thanks! You can test my [fork](https://github.com/ruslangallo/gulp-pug-inheritance-test).

**Comment by pure180** [comment]
@ruslangallo i tested your fork, what exactly is wrong, cant find any bug? Exept that it need some time (approx 1min for approximately 30 files) to build the pug files for the first time. 

@adammockor I recognized that the delay is coming from the switch statement inside the iteration in version.js ([Line 14](https://github.com/adammockor/pug-inheritance/blob/master/src/version.coffee#L14)). I saved about 40 seconds in this case using an "if else" statement. But we can also decide to drop the support for deprecated pug/jade versions.

#11

**Comment by pure180** [comment]
#11

**Comment by ruslanxdev** [comment]
@pure180 Thank you) Yea, I worry especially about the time. It's too big gulp)

Maybe not check version, and set it in the options? But I think Jade is no longer treat this plugin. When I had Jade, I used [jade-inheritance](https://github.com/paulyoung/jade-inheritance).

**Comment by pure180** [comment]
There is also PugJS in version [1.10.0](https://github.com/pugjs/pug/releases?after=1.11.0), which doesn't support code blocks. (https://github.com/juanfran/gulp-jade-inheritance/issues/13) 

Pug-Walk supports to methods to consider included files, `Include` ([Line 67](https://github.com/pugjs/pug-walk/blob/master/index.js#L67)) and `RawInclude` ([Line 74](https://github.com/pugjs/pug-walk/blob/master/index.js#L74)). `Include` it self doesn't support code blocks as well and it is a bit slower then `RawInclude`.

@adammockor ... I suggest to drop deprecated support, but giving the devs the options to set a deprecated flag to use older versions that dont support code blocks, by choosing the pug-walk ast type.
